const express = require('express');
const { prisma } = require('../db.cjs');
const { PERMISSIONS, requirePermission } = require('../rbac.cjs');

const router = express.Router();

// Get AI Config
router.get('/config', requirePermission(PERMISSIONS.SETTINGS_READ), async (req, res) => {
  try {
    const configs = await prisma.aIIntegration.findMany();
    return res.json({ configs });
  } catch (error) {
    console.error('Get AI config error:', error);
    return res.status(500).json({ error: 'Server error' });
  }
});

// Update AI Config
router.put('/config/:provider', requirePermission(PERMISSIONS.SETTINGS_UPDATE), async (req, res) => {
  try {
    const { provider } = req.params;
    const { isEnabled, apiKey, model } = req.body;
    
    // Upsert logic
    const existing = await prisma.aIIntegration.findFirst({ where: { provider } });
    
    let result;
    if (existing) {
      result = await prisma.aIIntegration.update({
        where: { id: existing.id },
        data: { isEnabled, apiKey, model }
      });
    } else {
      result = await prisma.aIIntegration.create({
        data: {
          provider,
          isEnabled,
          apiKey,
          model,
          features: JSON.stringify(['content']),
          quota: 1000,
          used: 0
        }
      });
    }
    
    return res.json({ config: result });
  } catch (error) {
    console.error('Update AI config error:', error);
    return res.status(500).json({ error: 'Server error' });
  }
});

// Generate Content
router.post('/generate', requirePermission(PERMISSIONS.CONTENT_CREATE), async (req, res) => {
  try {
    const { prompt, type, provider = 'openai' } = req.body;
    
    const config = await prisma.aIIntegration.findFirst({ where: { provider, isEnabled: true } });
    if (!config || !config.apiKey) {
      return res.status(400).json({ error: 'AI provider not configured or disabled' });
    }
    
    // Mock generation for now
    let generatedText = '';
    if (provider === 'openai') {
       generatedText = `[AI Generated Content for ${type}]\n\nBased on prompt: "${prompt}"\n\nHere is a draft content generated by AI. You can edit this text.`;
    } else {
       generatedText = `[AI Generated Content for ${type}]\n\nBased on prompt: "${prompt}"\n\nHere is a draft content generated by AI. You can edit this text.`;
    }
    
    // Log usage
    await prisma.aIIntegration.update({
      where: { id: config.id },
      data: { used: (config.used || 0) + 1 }
    });
    
    return res.json({ text: generatedText });
  } catch (error) {
    console.error('AI generate error:', error);
    return res.status(500).json({ error: 'Server error' });
  }
});

module.exports = router;
